name: Deploy Spring Boot to EC2 (Ubuntu)

on:
  push:                                   
    branches:
      - main                              

jobs:
  build-and-deploy:                       
    runs-on: ubuntu-latest                
    env:
      DB_ENDPOINT: ${{ secrets.DB_ENDPOINT }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: temurin

      - name: Build and test with Maven
        run: |
            mvn clean package        
            mvn test                

      - name: Copy .war to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: target/demo-0.0.1-SNAPSHOT.war
          target: /home/ubuntu/
          strip_components: 1

      - name: Configure environment variables and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            echo "export DB_ENDPOINT=${{ secrets.DB_ENDPOINT }}" | sudo tee -a /etc/environment
            echo "export DB_USERNAME=${{ secrets.DB_USERNAME }}" | sudo tee -a /etc/environment
            echo "export DB_PASSWORD=${{ secrets.DB_PASSWORD }}" | sudo tee -a /etc/environment
            
            source /etc/environment

            sudo mv /home/ubuntu/demo-0.0.1-SNAPSHOT.war /var/lib/tomcat10/webapps/demo.war  

            sudo chown tomcat:tomcat /var/lib/tomcat10/webapps/demo.war  
            sudo chmod 755 /var/lib/tomcat10/webapps/demo.war 

            sudo systemctl restart tomcat10


